import { createSupabaseAdminClient } from "@/lib/supabase/server-admin";
import { getWorkspaceContext } from "@/server/services/workspace-context";
import { getQuoteMarginGuard, getQuoteVersionComparison } from "@/server/services/sales-growth-v6";
import { getLatestQuoteVersionDiff } from "@/server/services/quote-version-diff-v6";
import { decideDiscountApprovalAction, requestDiscountApprovalAction, snapshotQuoteVersionAction } from "../actions";

type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> };

export default async function QuoteGovernancePage({ searchParams }: Props) {
  const params = await searchParams;
  const quoteId = typeof params.quote === "string" ? params.quote : "";
  const context = await getWorkspaceContext();
  const admin = createSupabaseAdminClient();
  const approvals = context.mode === "live" ? (await admin.from("quote_discount_approvals").select("id,quote_id,discount_percent,reason,status,created_at").eq("organization_id", context.organization.id).order("created_at", { ascending: false }).limit(100)).data || [] : [];
  const quotes = context.mode === "live" ? (await admin.from("quotes").select("id,quote_number,status,total,subtotal,discount_total").eq("organization_id", context.organization.id).order("created_at", { ascending: false }).limit(100)).data || [] : [];
  const margin = quoteId && context.mode === "live" ? await getQuoteMarginGuard(context.organization.id, quoteId).catch(() => null) : null;
  const versions = quoteId && context.mode === "live" ? await getQuoteVersionComparison(context.organization.id, quoteId).catch(() => []) : [];
  const diff = quoteId && context.mode === "live" ? await getLatestQuoteVersionDiff(context.organization.id, quoteId).catch(() => null) : null;
  return <div className="space-y-6">
    <div><h1 className="text-3xl font-bold text-slate-900">Teklif Yönetişimi</h1><p className="mt-2 text-slate-500">Marj koruması, indirim onayı, sürüm geçmişi ve değişiklik farklarını tek ekranda yönetin.</p></div>
    <form className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-4"><select name="quote" defaultValue={quoteId} className="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Teklif seçin</option>{quotes.map((quote) => <option key={quote.id} value={quote.id}>{quote.quote_number} · {quote.status}</option>)}</select><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">İncele</button></form>
    {quoteId && <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Marj koruması</h2>{margin ? <div className="mt-4 space-y-2 text-sm"><Row label="Gelir" value={`${margin.revenue.toLocaleString("tr-TR")} TL`}/><Row label="Doğrulanmış maliyet" value={margin.costComplete ? `${margin.cost.toLocaleString("tr-TR")} TL` : "Eksik"}/><Row label="Marj" value={margin.marginPercent === null ? "Doğrulanamıyor" : `%${margin.marginPercent}`}/><p className={margin.guarded ? "text-amber-700" : "text-emerald-700"}>{margin.reason}</p></div> : <p className="mt-3 text-sm text-slate-500">Marj verisi yüklenemedi.</p>}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Yeni indirim onayı</h2><form action={requestDiscountApprovalAction} className="mt-4 space-y-3"><input type="hidden" name="quoteId" value={quoteId}/><input name="discountPercent" type="number" min="0.01" max="100" step="0.01" required placeholder="İndirim %" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><textarea name="reason" required placeholder="İndirim gerekçesi" className="min-h-24 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Onaya gönder</button></form></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold text-slate-900">Teklif sürümleri</h2><p className="text-sm text-slate-500">Her snapshot teklif ve satırlarını birlikte saklar.</p></div><form action={snapshotQuoteVersionAction} className="flex gap-2"><input type="hidden" name="quoteId" value={quoteId}/><input name="changeNote" placeholder="Değişiklik notu" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/><button className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-medium">Snapshot al</button></form></div><div className="mt-4 space-y-2">{versions.map((version) => <div key={version.id} className="rounded-xl border border-slate-100 p-3 text-sm"><span className="font-semibold text-slate-900">v{version.version_number}</span><span className="ml-3 text-slate-500">{version.change_note || "Not yok"} · {new Date(version.created_at).toLocaleString("tr-TR")}</span></div>)}{!versions.length && <p className="text-sm text-slate-500">Henüz sürüm snapshot’ı yok.</p>}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><h2 className="font-semibold text-slate-900">Son iki sürüm arasındaki fark</h2>{diff && diff.from ? <div className="mt-4 space-y-2">{diff.changes.map((change) => <div key={change.field} className="grid gap-2 rounded-xl border border-slate-100 p-3 text-sm md:grid-cols-[180px_1fr_1fr]"><span className="font-medium text-slate-900">{change.field}</span><span className="text-rose-600">{change.before || "—"}</span><span className="text-emerald-700">{change.after || "—"}</span></div>)}{!diff.changes.length && <p className="text-sm text-slate-500">Son iki snapshot arasında izlenen alanlarda değişiklik yok.</p>}</div> : <p className="mt-3 text-sm text-slate-500">Karşılaştırma için en az iki snapshot gerekir.</p>}</section>
    </div>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">İndirim onay kuyruğu</h2><div className="mt-4 space-y-3">{approvals.map((approval) => <div key={approval.id} className="flex flex-col justify-between gap-3 rounded-xl border border-slate-100 p-3 md:flex-row md:items-center"><div><div className="font-medium text-slate-900">%{Number(approval.discount_percent).toLocaleString("tr-TR")} indirim · {approval.status}</div><div className="text-sm text-slate-500">{approval.reason}</div></div>{approval.status === "pending" && ["owner","admin"].includes(context.role) ? <form action={decideDiscountApprovalAction} className="flex gap-2"><input type="hidden" name="approvalId" value={approval.id}/><button name="decision" value="approved" className="rounded-lg border border-emerald-300 px-3 py-2 text-sm font-medium text-emerald-700">Onayla</button><button name="decision" value="rejected" className="rounded-lg border border-rose-300 px-3 py-2 text-sm font-medium text-rose-700">Reddet</button></form> : null}</div>)}{!approvals.length && <p className="text-sm text-slate-500">İndirim onayı bulunmuyor.</p>}</div></section>
  </div>;
}

function Row({label,value}:{label:string;value:string}) { return <div className="flex justify-between gap-4"><span className="text-slate-500">{label}</span><span className="font-medium text-slate-900">{value}</span></div>; }