"use client";

import { useState } from "react";
import Link from "next/link";
import { Mail, RefreshCw, Unplug } from "lucide-react";

type Connection = { id: string; provider: string; email_address: string; display_name: string | null; status: string; last_synced_at: string | null; error_message?: string | null };

export function EmailConnections({ connections, canManage, gmailConfigured, microsoftConfigured }: { connections: Connection[]; canManage: boolean; gmailConfigured: boolean; microsoftConfigured: boolean }) {
  const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  async function disconnect(id: string) { if (!confirm("Bu e-posta hesabının bağlantısı kaldırılsın mı?")) return; setBusy(id); const response = await fetch("/api/email", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "disconnect", connectionId: id }) }); const data = await response.json(); if (!response.ok) { setError(data.message); setBusy(""); return; } window.location.reload(); }
  const cards = [{ provider: "gmail", label: "Gmail / Google Workspace", configured: gmailConfigured, color: "bg-red-500" }, { provider: "microsoft", label: "Microsoft 365 / Outlook", configured: microsoftConfigured, color: "bg-blue-600" }];
  return <div className="space-y-6">{error ? <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}<div className="grid gap-5 md:grid-cols-2">{cards.map((card) => <section key={card.provider} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-950"><div className="flex items-center gap-3"><span className={`grid h-11 w-11 place-items-center rounded-xl text-white ${card.color}`}><Mail className="h-5 w-5" /></span><div><h2 className="font-semibold text-slate-950 dark:text-white">{card.label}</h2><p className="text-xs text-slate-500">Gelen kutusu eşitleme ve e-posta gönderimi</p></div></div><div className="mt-5 space-y-3">{connections.filter((item) => item.provider === card.provider).map((item) => <div key={item.id} className="rounded-xl bg-slate-50 p-3 dark:bg-white/5"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-medium text-slate-900 dark:text-white">{item.display_name || item.email_address}</p><p className="text-xs text-slate-500">{item.email_address}</p></div><span className="rounded-full bg-emerald-100 px-2 py-1 text-[11px] font-semibold text-emerald-700">{item.status === "connected" ? "Bağlı" : item.status}</span></div>{canManage ? <button disabled={busy === item.id} onClick={() => disconnect(item.id)} className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-rose-600"><Unplug className="h-3.5 w-3.5" />Bağlantıyı kaldır</button> : null}</div>)}{canManage ? card.configured ? <a href={`/api/integrations/email/${card.provider}/connect`} className="inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-semibold text-white dark:bg-white dark:text-slate-950"><RefreshCw className="h-4 w-4" />{connections.some((item) => item.provider === card.provider) ? "Başka hesap bağla" : "Hesabı bağla"}</a> : <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Sağlayıcı anahtarları Vercel ortam değişkenlerinde yapılandırılmalı.</div> : <p className="text-xs text-slate-500">Bağlantıları yalnızca Owner veya Admin yönetebilir.</p>}</div></section>)}</div><Link href="/inbox/email" className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white"><Mail className="h-4 w-4" />E-posta Merkezini aç</Link></div>;
}
