import { createSupabaseAdminClient } from "@/lib/supabase/server-admin";
import { getWorkspaceContext } from "@/server/services/workspace-context";
import { createRoutingRuleAction, createSlaPolicyAction, toggleSalesPolicyAction } from "./actions";

export default async function SalesPoliciesPage() {
  const context = await getWorkspaceContext();
  const admin = createSupabaseAdminClient();
  const [sla, routing] = context.mode === "live" ? await Promise.all([
    admin.from("sales_sla_policies").select("id,name,lead_status,first_response_minutes,follow_up_minutes,active").eq("organization_id", context.organization.id).order("created_at", { ascending: false }),
    admin.from("sales_routing_rules").select("id,name,source,city,min_estimated_value,target_user_id,priority,active").eq("organization_id", context.organization.id).order("priority"),
  ]) : [{ data: [] }, { data: [] }];
  const canAdmin = context.mode === "live" && ["owner", "admin"].includes(context.role);
  return <div className="space-y-6">
    <div><h1 className="text-3xl font-bold text-slate-900">SLA ve Routing Politikaları</h1><p className="mt-2 text-slate-500">Yanıt sürelerini ve lead atama kurallarını merkezi olarak yönetin.</p></div>
    {canAdmin && <div className="grid gap-5 xl:grid-cols-2">
      <form action={createSlaPolicyAction} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">SLA politikası</h2><input required name="name" placeholder="Politika adı" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><select name="leadStatus" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="">Tüm statüler</option><option value="new">Yeni</option><option value="contacted">İletişim kuruldu</option><option value="qualified">Nitelikli</option><option value="quote_sent">Teklif gönderildi</option><option value="negotiation">Müzakere</option></select><div className="grid grid-cols-2 gap-3"><input required type="number" min="1" name="firstResponseMinutes" defaultValue="60" aria-label="İlk yanıt dakika" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/><input required type="number" min="1" name="followUpMinutes" defaultValue="1440" aria-label="Takip dakika" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/></div><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">SLA ekle</button></form>
      <form action={createRoutingRuleAction} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Routing kuralı</h2><input required name="name" placeholder="Kural adı" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-3"><input name="source" placeholder="Kaynak (opsiyonel)" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/><input name="city" placeholder="Şehir (opsiyonel)" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/></div><input required name="targetUserId" placeholder="Hedef kullanıcı UUID" className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm"/><div className="grid grid-cols-2 gap-3"><input type="number" min="0" name="minEstimatedValue" placeholder="Min. değer" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/><input type="number" name="priority" defaultValue="100" aria-label="Kural önceliği" className="rounded-lg border border-slate-200 px-3 py-2 text-sm"/></div><button className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Routing ekle</button></form>
    </div>}
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">SLA kuralları</h2><div className="mt-4 space-y-3">{(sla.data || []).map((row) => <PolicyRow key={row.id} title={row.name} detail={`${row.lead_status || "tümü"} · ilk yanıt ${row.first_response_minutes} dk · takip ${row.follow_up_minutes} dk`} active={row.active} kind="sla" id={row.id} canAdmin={canAdmin}/>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-900">Routing kuralları</h2><div className="mt-4 space-y-3">{(routing.data || []).map((row) => <PolicyRow key={row.id} title={row.name} detail={`${row.source || "tüm kaynaklar"} · ${row.city || "tüm şehirler"} · hedef ${row.target_user_id || "yok"}`} active={row.active} kind="routing" id={row.id} canAdmin={canAdmin}/>)}</div></section>
    </div>
  </div>;
}

function PolicyRow({title,detail,active,kind,id,canAdmin}:{title:string;detail:string;active:boolean;kind:"sla"|"routing";id:string;canAdmin:boolean}) { return <div className="flex items-center justify-between gap-3 rounded-xl border border-slate-100 p-3"><div><div className="font-medium text-slate-900">{title}</div><div className="text-sm text-slate-500">{detail}</div></div>{canAdmin ? <form action={toggleSalesPolicyAction}><input type="hidden" name="kind" value={kind}/><input type="hidden" name="id" value={id}/><input type="hidden" name="active" value={active ? "false" : "true"}/><button className="rounded-lg border border-slate-300 px-3 py-2 text-xs font-medium">{active ? "Pasifleştir" : "Aktifleştir"}</button></form> : <span className="text-xs text-slate-500">{active ? "Aktif" : "Pasif"}</span>}</div>; }
